"""Export and import — the integration surface for other tools.

The dnsmasq exports emit exactly the JSON bodies DNSMAQ-MGR's own endpoints
accept (`/api/dns/hosts` and `/api/dhcp/static_leases`), so keeping a dnsmasq
instance in step with the address plan is a fetch-here / post-there loop with
no translation layer in between. The plain-text exports are for everything
else that reads a hosts file or a zone fragment.

Text output is built by concatenation, which is why core.validators refuses
line breaks in every stored field — a name containing a newline would
otherwise smuggle a second directive into someone's config.
"""
import json

from flask import Blueprint, Response, jsonify, request

from .core import db
from .core.auth import actor
from .core.runcmd import err, num

bp = Blueprint('exports', __name__)

# Tables included in a full dump/restore, in dependency order so a restore
# never violates a foreign key.
DUMP_TABLES = ('vlans', 'networks', 'clusters', 'devices', 'vms', 'containers',
               'dhcp_servers', 'dns_servers', 'dhcp_ranges', 'ip_addresses')


def _named_addresses():
    """Address records that carry a DNS name — the source for every name-based
    export."""
    return db.query(
        "SELECT ip_addresses.address, ip_addresses.version, ip_addresses.dns_name, "
        "       ip_addresses.mac, ip_addresses.description, networks.domain "
        "FROM ip_addresses LEFT JOIN networks ON networks.id = ip_addresses.network_id "
        "WHERE ip_addresses.dns_name <> '' AND ip_addresses.status IN ('active','reserved') "
        "ORDER BY ip_addresses.version, ip_addresses.addr_hex")


def _fqdn(rec):
    """Qualify a bare hostname with its network's domain when it has one."""
    name = rec['dns_name']
    domain = (rec.get('domain') or '').strip()
    if domain and '.' not in name:
        return '%s.%s' % (name, domain)
    return name


@bp.route('/api/export/hosts')
def export_hosts():
    """A standard unix hosts file. DNSMAQ-MGR's DNS page imports this format
    directly, and so does every other tool on earth."""
    lines = ['# Generated by Nexus IPAM', '']
    for rec in _named_addresses():
        lines.append('%-39s %s' % (rec['address'], _fqdn(rec)))
    return Response('\n'.join(lines) + '\n', mimetype='text/plain')


@bp.route('/api/export/dnsmasq/hosts')
def export_dnsmasq_hosts():
    """Host records in DNSMAQ-MGR's `/api/dns/hosts` body shape: one object per
    name with its A and/or AAAA. A sync script POSTs these straight across."""
    by_name = {}
    for rec in _named_addresses():
        name = _fqdn(rec)
        entry = by_name.setdefault(name, {'name': name, 'a': '', 'aaaa': '',
                                          'comment': 'from Nexus IPAM'})
        entry['aaaa' if rec['version'] == 6 else 'a'] = rec['address']
    return jsonify({'hosts': list(by_name.values()), 'count': len(by_name)})


@bp.route('/api/export/dnsmasq/static-leases')
def export_dnsmasq_leases():
    """Reservations in DNSMAQ-MGR's `/api/dhcp/static_leases` body shape.
    Only records with a MAC qualify — a static lease without one is meaningless.
    """
    out = []
    for rec in db.query(
            "SELECT address, dns_name, mac, description FROM ip_addresses "
            "WHERE mac <> '' AND version = 4 AND status IN ('active','reserved') "
            "ORDER BY addr_hex"):
        out.append({'mac': rec['mac'], 'ip': rec['address'],
                    'hostname': rec['dns_name'].split('.')[0] if rec['dns_name'] else '',
                    'comment': 'from Nexus IPAM'})
    return jsonify({'static_leases': out, 'count': len(out)})


@bp.route('/api/export/zone')
def export_zone():
    """A BIND-style A/AAAA record fragment for one domain. Deliberately just
    the records — SOA and NS belong to whoever owns the zone file."""
    domain = (request.args.get('domain') or '').strip().rstrip('.')
    if not domain:
        return err('A domain is required, e.g. /api/export/zone?domain=lan')
    from .core.validators import valid_fqdn
    if not valid_fqdn(domain):
        return err('Invalid domain')
    lines = ['; Generated by Nexus IPAM — records for %s' % domain, '']
    for rec in _named_addresses():
        fqdn = _fqdn(rec)
        if not fqdn.endswith('.' + domain) and fqdn != domain:
            continue
        label = fqdn[:-(len(domain) + 1)] or '@'
        lines.append('%-30s IN  %-5s %s' % (label, 'AAAA' if rec['version'] == 6 else 'A',
                                            rec['address']))
    return Response('\n'.join(lines) + '\n', mimetype='text/plain')


@bp.route('/api/export/csv')
def export_csv():
    """Flat address inventory for spreadsheets and diffing."""
    import csv
    import io
    from .addresses import ADDRESS_LIST_SQL, expand_assignment
    rows = db.rows(ADDRESS_LIST_SQL + ' ORDER BY ip_addresses.version, ip_addresses.addr_hex')
    buf = io.StringIO()
    cols = ['address', 'network_cidr', 'vlan_vid', 'status', 'dns_name', 'mac',
            'assigned_kind', 'assigned_name', 'if_name', 'source', 'description']
    w = csv.DictWriter(buf, fieldnames=cols, extrasaction='ignore')
    w.writeheader()
    for r in rows:
        expand_assignment(r)
        w.writerow(r)
    return Response(buf.getvalue(), mimetype='text/csv',
                    headers={'Content-Disposition': 'attachment; filename=nexus-ipam.csv'})


@bp.route('/api/export/json')
def export_json():
    """Full dump — a backup, and the thing to diff when a sync goes wrong."""
    from .core.config import APP_VERSION
    data = {'app': 'nexus-ipam', 'version': APP_VERSION,
            'exported': db.now(), 'tables': {}}
    for table in DUMP_TABLES:
        data['tables'][table] = db.query('SELECT * FROM %s ORDER BY id' % table)
    return Response(json.dumps(data, indent=2), mimetype='application/json',
                    headers={'Content-Disposition': 'attachment; filename=nexus-ipam.json'})


@bp.route('/api/import/json', methods=['POST'])
def import_json():
    """Restore a dump produced by /api/export/json.

    `mode=replace` wipes the existing data first; `mode=merge` (the default)
    inserts only rows whose id is not already present, so a restore cannot
    clobber newer local edits by surprise.
    """
    data = request.get_json(silent=True) or {}
    tables = data.get('tables')
    if not isinstance(tables, dict):
        return err('Expected a dump produced by /api/export/json')
    mode = request.args.get('mode', 'merge')
    if mode not in ('merge', 'replace'):
        return err('mode must be merge or replace')

    counts = {}
    with db.WRITE_LOCK:
        conn = db.connect()
        conn.execute('BEGIN')
        try:
            if mode == 'replace':
                # Reverse order: children before parents.
                for table in reversed(DUMP_TABLES):
                    conn.execute('DELETE FROM %s' % table)
            for table in DUMP_TABLES:
                rows = tables.get(table) or []
                if not isinstance(rows, list):
                    continue
                n = 0
                for row in rows:
                    if not isinstance(row, dict) or 'id' not in row:
                        continue
                    if mode == 'merge' and conn.execute(
                            'SELECT 1 FROM %s WHERE id=?' % table, (row['id'],)).fetchone():
                        continue
                    cols = [c for c in row if c != 'rowid']
                    conn.execute(
                        'INSERT OR REPLACE INTO %s (%s) VALUES (%s)'
                        % (table, ', '.join(cols), ', '.join('?' for _ in cols)),
                        tuple(row[c] for c in cols))
                    n += 1
                counts[table] = n
            conn.execute('COMMIT')
        except Exception as ex:
            conn.execute('ROLLBACK')
            return err('Import failed and was rolled back: %s' % ex, 400)

    from .networks import reindex_addresses
    reindex_addresses()
    db.audit(actor(), 'import', 'database', None,
             '%s: %s' % (mode, ', '.join('%s=%d' % kv for kv in counts.items())))
    return jsonify({'success': True, 'mode': mode, 'imported': counts})


@bp.route('/api/changes')
def changes():
    """Incremental change feed: everything modified since a timestamp.

    This is how an external system stays in sync without polling every table
    in full — pass the `now` value from the previous response as `since` on
    the next call. Deletions are not tracked here; a periodic full compare
    against /api/export/json covers those.
    """
    since = num(request.args.get('since'))
    if since is None:
        return err('A since=<unix timestamp> parameter is required')
    out = {}
    for table in DUMP_TABLES:
        out[table] = db.rows('SELECT * FROM %s WHERE updated >= ? ORDER BY updated'
                             % table, (since,))
    total = sum(len(v) for v in out.values())
    return jsonify({'since': since, 'now': db.now(), 'count': total, 'changes': out})


@bp.route('/api/audit')
def audit_log():
    limit = max(1, min(num(request.args.get('limit')) or 200, 2000))
    from .core.config import AUDIT_DAYS
    return jsonify({'audit': db.query('SELECT * FROM audit ORDER BY ts DESC, id DESC LIMIT ?',
                                      (limit,)),
                    'retention_days': AUDIT_DAYS,
                    **db.audit_stats()})


@bp.route('/api/audit/prune', methods=['POST'])
def audit_prune():
    """Manual prune (admin-only via the central RBAC — this is a POST).
    Body: {"days": N} keeps the last N days; {"all": true} empties the log.
    The manual path VACUUMs so a big clear-out actually returns the disk;
    the daily automatic prune deliberately does not (freed pages get reused,
    which is all bounded growth needs)."""
    data = request.get_json(silent=True) or {}
    if data.get('all'):
        deleted = db.prune_audit(everything=True, vacuum=True)
        detail = 'all %d entries' % deleted
    else:
        days = num(data.get('days'))
        if days is None or days < 1:
            return err('Pass {"days": N} (N >= 1) or {"all": true}')
        deleted = db.prune_audit(days=days, vacuum=True)
        detail = '%d entries older than %dd' % (deleted, days)
    # The prune itself is auditable — an emptied log that says why it is
    # empty beats one that just is.
    db.audit(actor(), 'prune-audit', 'audit', None, detail)
    return jsonify({'success': True, 'deleted': deleted, **db.audit_stats()})
